<?php
require __DIR__.'/bootstrap.php';$admin=require_role('admin');$action=$_GET['action']??'';
if(method()==='GET'){
 if($action==='counts'){$row=$db->query("SELECT (SELECT COUNT(*) FROM seller_profiles WHERE verification_status='pending') pending_sellers,(SELECT COUNT(*) FROM products WHERE status='pending') pending_listings,(SELECT COUNT(*) FROM auctions WHERE status='live') live_auctions,(SELECT COUNT(*) FROM fraud_reports WHERE status IN('open','investigating')) fraud_alerts,(SELECT COUNT(*) FROM deliveries WHERE status<>'delivered') active_deliveries,(SELECT COUNT(*) FROM notifications WHERE user_id=".(int)$admin['id']." AND read_at IS NULL) unread_notifications")->fetch_assoc();ok($row);}
 if($action==='listings'){$rows=$db->query("SELECT p.id,p.title,p.description,p.status,p.sale_type,p.price,p.condition_label,p.location,p.shipping_days,p.created_at,c.name category,CONCAT(u.first_name,' ',u.last_name) seller,pi.image_url image FROM products p JOIN categories c ON c.id=p.category_id JOIN users u ON u.id=p.seller_id LEFT JOIN product_images pi ON pi.product_id=p.id AND pi.is_primary=1 ORDER BY FIELD(p.status,'pending','active','paused','sold','rejected'),p.created_at DESC")->fetch_all(MYSQLI_ASSOC);foreach($rows as &$row){$stmt=$db->prepare('SELECT id,original_name FROM product_documents WHERE product_id=? ORDER BY created_at,id');$stmt->bind_param('i',$row['id']);$row['documents']=db_all($stmt);}ok($rows);}
 if($action==='sellers'){$rows=$db->query("SELECT u.id,u.first_name,u.last_name,CONCAT(u.first_name,' ',u.last_name) name,u.email,u.phone,u.status,sp.business_name,sp.business_description,sp.nid_document,sp.trade_license,sp.verification_status,sp.rating,sp.rating_count,u.created_at FROM users u JOIN roles r ON r.id=u.role_id AND r.name='seller' LEFT JOIN seller_profiles sp ON sp.user_id=u.id ORDER BY FIELD(sp.verification_status,'pending','approved','rejected'),u.created_at DESC")->fetch_all(MYSQLI_ASSOC);ok($rows);}
 if($action==='deliveries')ok($db->query('SELECT d.*,o.order_number,o.shipping_name FROM deliveries d JOIN orders o ON o.id=d.order_id ORDER BY d.updated_at DESC')->fetch_all(MYSQLI_ASSOC));
 if($action==='fraud')ok($db->query("SELECT f.*,CONCAT(u.first_name,' ',u.last_name) reporter FROM fraud_reports f JOIN users u ON u.id=f.reporter_id ORDER BY f.created_at DESC")->fetch_all(MYSQLI_ASSOC));
 if($action==='settings'){ $rows=$db->query('SELECT setting_key,setting_value FROM system_settings')->fetch_all(MYSQLI_ASSOC);$out=[];foreach($rows as $r)$out[$r['setting_key']]=$r['setting_value'];ok($out); }
 if($action==='wallet'){$row=$db->query("SELECT (SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE status NOT IN('cancelled','rejected')) volume,(SELECT COALESCE(SUM(amount),0) FROM commissions) commission,(SELECT COALESCE(SUM(pending_balance),0) FROM wallets) pending_payouts")->fetch_assoc();ok($row);}
 if($action==='orders')ok($db->query("SELECT o.order_number,o.total_amount,o.status,o.placed_at,oi.title_snapshot,CONCAT(s.first_name,' ',s.last_name) seller,COALESCE(sp.rating,0) rating,pi.image_url image FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN users s ON s.id=oi.seller_id LEFT JOIN seller_profiles sp ON sp.user_id=s.id LEFT JOIN product_images pi ON pi.product_id=oi.product_id AND pi.is_primary=1 ORDER BY o.placed_at DESC LIMIT 10")->fetch_all(MYSQLI_ASSOC));
 fail('Unknown admin resource.',404);
}
$in=input();
if(method()==='PATCH'&&$action==='listing'){$id=int_value($in['id']??null);$status=$in['status']??'';if(!in_array($status,['active','rejected','paused'],true))fail('Invalid listing status.',422);$aid=(int)$admin['id'];$db->begin_transaction();try{$stmt=$db->prepare('UPDATE products SET status=?,approved_by=?,approved_at=IF(?=\'active\',NOW(),approved_at) WHERE id=?');$stmt->bind_param('sisi',$status,$aid,$status,$id);$stmt->execute();if($status==='active'){$stmt=$db->prepare("UPDATE auctions SET status='live',starts_at=NOW(),ends_at=IF(ends_at<=NOW(),DATE_ADD(NOW(),INTERVAL 7 DAY),ends_at) WHERE product_id=? AND status='scheduled'");$stmt->bind_param('i',$id);$stmt->execute();$stmt=$db->prepare("INSERT IGNORE INTO auctions(product_id,starting_price,bid_increment,current_price,buy_now_price,starts_at,ends_at,status) SELECT id,price,10,price,NULL,NOW(),DATE_ADD(NOW(),INTERVAL 7 DAY),'live' FROM products WHERE id=? AND sale_type='auction'");$stmt->bind_param('i',$id);$stmt->execute();}$db->commit();ok(null,'Listing moderation saved.');}catch(Throwable $e){$db->rollback();throw $e;}}
if(method()==='PATCH'&&$action==='seller'){$id=int_value($in['id']??null);$status=$in['status']??'';if(!in_array($status,['approved','rejected'],true))fail('Invalid seller status.',422);$userStatus=$status==='approved'?'active':'rejected';$db->begin_transaction();try{$stmt=$db->prepare('UPDATE seller_profiles SET verification_status=?,approved_at=IF(?=\'approved\',NOW(),approved_at) WHERE user_id=?');$stmt->bind_param('ssi',$status,$status,$id);$stmt->execute();$stmt=$db->prepare('UPDATE users SET status=? WHERE id=?');$stmt->bind_param('si',$userStatus,$id);$stmt->execute();$db->commit();ok(null,'Seller moderation saved.');}catch(Throwable $e){$db->rollback();throw $e;}}
if(method()==='PATCH'&&$action==='settings'){foreach(['standard_commission','auction_commission','minimum_commission','withdrawal_fee'] as $key){if(!isset($in[$key]))continue;$val=(string)max(0,(float)$in[$key]);$aid=(int)$admin['id'];$stmt=$db->prepare('INSERT INTO system_settings(setting_key,setting_value,updated_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)');$stmt->bind_param('ssi',$key,$val,$aid);$stmt->execute();}ok(null,'Settings saved.');}
fail('Method not allowed.',405);
