<?php
require __DIR__.'/bootstrap.php';close_ended_auctions($db);
if(method()==='GET'){
 $id=$_GET['id']??null;$slug=trim((string)($_GET['slug']??''));$scope=$_GET['scope']??'';$mine=$scope==='mine';$all=$scope==='all';
 $sql="SELECT a.*,p.seller_id,p.slug,p.title,p.description,p.condition_label,p.brand,p.accessories,p.location,p.shipping_days,p.specifications,p.views,p.co2_saved_kg,c.name category,c.slug category_slug,u.first_name,u.last_name,COALESCE(sp.rating,0) seller_rating,COUNT(b.id) bid_count FROM auctions a JOIN products p ON p.id=a.product_id JOIN categories c ON c.id=p.category_id JOIN users u ON u.id=p.seller_id LEFT JOIN seller_profiles sp ON sp.user_id=p.seller_id LEFT JOIN bids b ON b.auction_id=a.id";
 $where=[];$types='';$params=[];if($id){$where[]='a.id=?';$types.='i';$params[]=int_value($id);}if($slug!==''){$where[]='p.slug=?';$types.='s';$params[]=$slug;}if($mine){$u=require_user();if($u['role']==='seller'){$where[]='p.seller_id=?';}else{$where[]='EXISTS(SELECT 1 FROM bids bx WHERE bx.auction_id=a.id AND bx.bidder_id=?)';}$types.='i';$params[]=(int)$u['id'];}if($all)require_role('admin');if(!$id&&$slug===''&&!$mine&&!$all)$where[]="a.status IN('live','scheduled')";
 if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' GROUP BY a.id ORDER BY a.ends_at';$stmt=$db->prepare($sql);if($types)$stmt->bind_param($types,...$params);$rows=db_all($stmt);
 foreach($rows as &$r){$st=$db->prepare('SELECT image_url FROM product_images WHERE product_id=? ORDER BY sort_order');$st->bind_param('i',$r['product_id']);$r['images']=array_column(db_all($st),'image_url');$r['specifications']=$r['specifications']?json_decode($r['specifications'],true):[];$viewer=user();$r['is_highest_bidder']=$viewer?(int)$r['highest_bidder_id']===(int)$viewer['id']:false;$r['can_purchase']=$r['status']==='ended'&&$r['highest_bidder_id']!==null&&($r['reserve_price']===null||(float)$r['current_price']>=(float)$r['reserve_price'])&&$viewer&&(int)$r['highest_bidder_id']===(int)$viewer['id'];if($viewer){$bidder=(int)$viewer['id'];$st=$db->prepare('SELECT MAX(amount) user_bid FROM bids WHERE auction_id=? AND bidder_id=?');$st->bind_param('ii',$r['id'],$bidder);$bid=db_one($st);$r['user_bid']=$bid['user_bid']??null;}if($id||$slug!==''){$st=$db->prepare("SELECT b.amount,b.placed_at,CONCAT(u.first_name,' ',LEFT(u.last_name,1),'.') bidder FROM bids b JOIN users u ON u.id=b.bidder_id WHERE b.auction_id=? ORDER BY b.amount DESC,b.placed_at DESC");$st->bind_param('i',$r['id']);$r['bids']=db_all($st);}}
 if($id||$slug!==''){if(!$rows)fail('Auction not found.',404);ok($rows[0]);}ok($rows);
}
if(method()==='POST'&&($_GET['action']??'')==='bid'){
 $u=require_role('buyer','admin');$in=input();$id=int_value($in['auction_id']??null,'auction');$amount=(float)($in['amount']??0);$uid=(int)$u['id'];$db->begin_transaction();
 try{$stmt=$db->prepare("SELECT a.*,p.seller_id,p.title FROM auctions a JOIN products p ON p.id=a.product_id WHERE a.id=? FOR UPDATE");$stmt->bind_param('i',$id);$a=db_one($stmt);if(!$a)fail('Auction not found.',404);if($a['status']!=='live'||strtotime($a['ends_at'])<=time())fail('This auction is not accepting bids.',409);if((int)$a['seller_id']===$uid)fail('Sellers cannot bid on their own listing.',403);$minimum=(float)$a['current_price']+(float)$a['bid_increment'];if($amount<$minimum)fail('Bid must be at least $'.number_format($minimum,2).'.',422);
  $previous=$a['highest_bidder_id']===null?0:(int)$a['highest_bidder_id'];$db->query('UPDATE bids SET is_winning=0 WHERE auction_id='.(int)$id);$stmt=$db->prepare('INSERT INTO bids(auction_id,bidder_id,amount,is_winning) VALUES(?,?,?,1)');$stmt->bind_param('iid',$id,$uid,$amount);$stmt->execute();$stmt=$db->prepare('UPDATE auctions SET current_price=?,highest_bidder_id=? WHERE id=?');$stmt->bind_param('dii',$amount,$uid,$id);$stmt->execute();if($previous&&$previous!==$uid)notify_user($db,$previous,'outbid','You were outbid','A higher bid was placed on '.$a['title'].'.',['auction_id'=>$id]);notify_user($db,(int)$a['seller_id'],'new_bid','New bid received','A $'.number_format($amount,2).' bid was placed on '.$a['title'].'.',['auction_id'=>$id]);$db->commit();ok(['current_price'=>$amount,'minimum_next_bid'=>$amount+(float)$a['bid_increment'],'highest_bidder_id'=>$uid,'bid_count'=>(int)$db->query('SELECT COUNT(*) count FROM bids WHERE auction_id='.(int)$id)->fetch_assoc()['count']],'Bid placed.',201);
 }catch(Throwable $e){$db->rollback();throw $e;}
}
$admin=require_role('admin');$in=input();if(method()==='PATCH'){$id=int_value($in['id']??null);$status=$in['status']??'';if(!in_array($status,['live','paused','cancelled'],true))fail('Invalid auction status.',422);$stmt=$db->prepare('UPDATE auctions SET status=? WHERE id=?');$stmt->bind_param('si',$status,$id);$stmt->execute();ok(null,'Auction updated.');}fail('Method not allowed.',405);
