<?php
require __DIR__.'/bootstrap.php';$u=require_user();$uid=(int)$u['id'];$role=$u['role'];
if(($_GET['action']??'')==='analytics'){
 if($role==='seller'){$stmt=$db->prepare("SELECT DATE_FORMAT(o.placed_at,'%Y-%m') month,ROUND(SUM(oi.unit_price*oi.quantity),2) total FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.seller_id=? AND o.placed_at>=DATE_SUB(CURDATE(),INTERVAL 6 MONTH) GROUP BY DATE_FORMAT(o.placed_at,'%Y-%m') ORDER BY month");$stmt->bind_param('i',$uid);ok(db_all($stmt));}
 if($role==='buyer'){$stmt=$db->prepare("SELECT DATE_FORMAT(placed_at,'%Y-%m') month,ROUND(SUM(total_amount),2) total FROM orders WHERE buyer_id=? AND placed_at>=DATE_SUB(CURDATE(),INTERVAL 6 MONTH) GROUP BY DATE_FORMAT(placed_at,'%Y-%m') ORDER BY month");$stmt->bind_param('i',$uid);ok(db_all($stmt));}
 require_role('admin');ok($db->query("SELECT DATE_FORMAT(placed_at,'%Y-%m') month,ROUND(SUM(total_amount),2) total FROM orders WHERE placed_at>=DATE_SUB(CURDATE(),INTERVAL 6 MONTH) GROUP BY DATE_FORMAT(placed_at,'%Y-%m') ORDER BY month")->fetch_all(MYSQLI_ASSOC));
}
if($role==='buyer'){
 $stmt=$db->prepare('SELECT COUNT(*) orders,COALESCE(SUM(total_amount),0) spent FROM orders WHERE buyer_id=?');$stmt->bind_param('i',$uid);$stats=db_one($stmt);$stmt=$db->prepare("SELECT COUNT(DISTINCT CASE WHEN a.status='live' THEN a.id END) active_bids,COUNT(DISTINCT CASE WHEN a.status='ended' AND a.highest_bidder_id=? THEN a.id END) won_auctions FROM bids b JOIN auctions a ON a.id=b.auction_id WHERE b.bidder_id=?");$stmt->bind_param('ii',$uid,$uid);$stats+=db_one($stmt);$stmt=$db->prepare('SELECT COUNT(*) wishlist FROM wishlist_items WHERE user_id=?');$stmt->bind_param('i',$uid);$stats+=db_one($stmt);
}elseif($role==='seller'){
 $stmt=$db->prepare("SELECT COUNT(*) listings,SUM(status='active') active_listings,SUM(status='pending') pending_listings,COALESCE(SUM(views),0) profile_views FROM products WHERE seller_id=?");$stmt->bind_param('i',$uid);$stats=db_one($stmt);$stmt=$db->prepare('SELECT COUNT(*) orders,COALESCE(SUM(oi.unit_price*oi.quantity),0) revenue FROM order_items oi WHERE oi.seller_id=?');$stmt->bind_param('i',$uid);$stats+=db_one($stmt);
 $stmt=$db->prepare("SELECT COUNT(*) live_auctions,COALESCE(MAX(a.current_price),0) highest_bid FROM auctions a JOIN products p ON p.id=a.product_id WHERE p.seller_id=? AND a.status='live'");$stmt->bind_param('i',$uid);$stats+=db_one($stmt);
 $stmt=$db->prepare('SELECT COALESCE(sp.rating,0) rating,(SELECT COALESCE(SUM(c.amount),0) FROM commissions c JOIN order_items oi ON oi.id=c.order_item_id WHERE oi.seller_id=?) commission FROM seller_profiles sp WHERE sp.user_id=?');$stmt->bind_param('ii',$uid,$uid);$extra=db_one($stmt);if($extra)$stats+=$extra;
 $stmt=$db->prepare('SELECT COUNT(*) favorites FROM wishlist_items w JOIN products p ON p.id=w.product_id WHERE p.seller_id=?');$stmt->bind_param('i',$uid);$stats+=db_one($stmt);$stmt=$db->prepare('SELECT c.name FROM products p JOIN categories c ON c.id=p.category_id WHERE p.seller_id=? GROUP BY c.id,c.name ORDER BY COUNT(*) DESC LIMIT 1');$stmt->bind_param('i',$uid);$top=db_one($stmt);$stats['top_category']=$top['name']??null;$stmt=$db->prepare('SELECT title,views FROM products WHERE seller_id=? ORDER BY views DESC LIMIT 1');$stmt->bind_param('i',$uid);$stats['best_listing']=db_one($stmt);
}else{
 $stats=$db->query("SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM users WHERE status='pending') pending_users,(SELECT COUNT(*) FROM products) listings,(SELECT COUNT(*) FROM products WHERE status='pending') pending_listings,(SELECT COUNT(*) FROM orders) orders,(SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE status NOT IN('cancelled','rejected')) volume,(SELECT COALESCE(SUM(amount),0) FROM commissions) commission,(SELECT COUNT(*) FROM fraud_reports WHERE status IN('open','investigating')) fraud_alerts")->fetch_assoc();
}
$stmt=$db->prepare('SELECT available_balance,pending_balance,currency FROM wallets WHERE user_id=?');$stmt->bind_param('i',$uid);$stats['wallet']=db_one($stmt);ok($stats);
