<?php
require __DIR__.'/bootstrap.php';$u=require_user();$uid=(int)$u['id'];$action=$_GET['action']??'';if(method()==='POST'&&$action==='checkout')close_ended_auctions($db);
if(method()==='GET'){
 if($u['role']==='seller'){$stmt=$db->prepare("SELECT o.id,o.order_number,o.status,o.total_amount,o.shipping_amount,o.shipping_address,o.placed_at,o.shipping_name,oi.id item_id,oi.product_id,oi.title_snapshot,oi.unit_price,oi.quantity,oi.status item_status,p.condition_label,p.sale_type,p.location,p.description,c.name category,pi.image_url image,d.tracking_number,d.status delivery_status FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id JOIN categories c ON c.id=p.category_id LEFT JOIN product_images pi ON pi.product_id=p.id AND pi.is_primary=1 LEFT JOIN deliveries d ON d.order_id=o.id WHERE oi.seller_id=? ORDER BY o.placed_at DESC");$stmt->bind_param('i',$uid);ok(db_all($stmt));}
 $stmt=$db->prepare("SELECT o.*,d.carrier,d.tracking_number,d.status delivery_status,d.estimated_delivery,d.delivered_at FROM orders o LEFT JOIN deliveries d ON d.order_id=o.id WHERE o.buyer_id=? ORDER BY o.placed_at DESC");$stmt->bind_param('i',$uid);$orders=db_all($stmt);foreach($orders as &$order){$itemStmt=$db->prepare("SELECT oi.id,oi.product_id,oi.title_snapshot,oi.unit_price,oi.quantity,oi.status,pi.image_url image,p.slug,p.condition_label,p.sale_type FROM order_items oi JOIN products p ON p.id=oi.product_id LEFT JOIN product_images pi ON pi.product_id=p.id AND pi.is_primary=1 WHERE oi.order_id=?");$itemStmt->bind_param('i',$order['id']);$order['items']=db_all($itemStmt);}ok($orders);
}
if(method()==='POST'&&$action==='checkout'){
 require_role('buyer','admin');$in=input();$name=text_value($in,'shipping_name',160);$email=text_value($in,'shipping_email',190);$phone=text_value($in,'shipping_phone',30);$address=text_value($in,'shipping_address',1000);$payment=$in['payment_method']??'card';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($payment,['card','wallet','cash_on_delivery'],true))fail('Invalid checkout details.',422);
 $requested=$in['items']??[];$db->begin_transaction();
 try{
  if(!$requested){$stmt=$db->prepare('SELECT ci.product_id,ci.quantity FROM carts c JOIN cart_items ci ON ci.cart_id=c.id WHERE c.user_id=?');$stmt->bind_param('i',$uid);$requested=db_all($stmt);}if(!$requested)fail('Your cart is empty.',422);
  $items=[];$subtotal=0;foreach($requested as $it){$pid=int_value($it['product_id']??null,'product');$qty=max(1,(int)($it['quantity']??1));$stmt=$db->prepare("SELECT p.id,p.seller_id,p.title,p.price,p.quantity,p.status,p.sale_type,a.id auction_id,a.current_price,a.reserve_price,a.highest_bidder_id,a.status auction_status FROM products p LEFT JOIN auctions a ON a.product_id=p.id WHERE p.id=? FOR UPDATE");$stmt->bind_param('i',$pid);$p=db_one($stmt);if(!$p)fail('One or more products are unavailable.',409);$isAuction=$p['sale_type']==='auction';$unitPrice=$isAuction?(float)$p['current_price']:(float)$p['price'];$winnerEligible=$isAuction&&$p['auction_status']==='ended'&&(int)$p['highest_bidder_id']===$uid&&($p['reserve_price']===null||$unitPrice>=(float)$p['reserve_price']);$productAvailable=$isAuction?in_array($p['status'],['active','paused'],true):$p['status']==='active';if(!$productAvailable||$qty>(int)$p['quantity']||$unitPrice<=0||($isAuction&&(!$winnerEligible||$qty!==1)))fail($isAuction?'Only the highest bidder can purchase this auction after it ends.':'One or more products are unavailable.',409);$p['unit_price']=$unitPrice;$p['buy_quantity']=$qty;$items[]=$p;$subtotal+=$unitPrice*$qty;}
  $shipping=15.00;$tax=0.00;$total=$subtotal+$shipping;if($payment==='wallet'){$stmt=$db->prepare('SELECT id,available_balance FROM wallets WHERE user_id=? FOR UPDATE');$stmt->bind_param('i',$uid);$wallet=db_one($stmt);if(!$wallet||(float)$wallet['available_balance']<$total)fail('Insufficient wallet balance.',409);$stmt=$db->prepare('UPDATE wallets SET available_balance=available_balance-? WHERE id=?');$stmt->bind_param('di',$total,$wallet['id']);$stmt->execute();}
  $number='RT-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(2)));$status=$payment==='cash_on_delivery'?'approved':'paid';$stmt=$db->prepare('INSERT INTO orders(order_number,buyer_id,subtotal,shipping_amount,tax_amount,total_amount,status,shipping_name,shipping_email,shipping_phone,shipping_address) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$stmt->bind_param('siddddsssss',$number,$uid,$subtotal,$shipping,$tax,$total,$status,$name,$email,$phone,$address);$stmt->execute();$oid=$stmt->insert_id;
  $settingRows=$db->query("SELECT setting_key,setting_value FROM system_settings WHERE setting_key IN('standard_commission','auction_commission','minimum_commission')")->fetch_all(MYSQLI_ASSOC);$settings=[];foreach($settingRows as $setting)$settings[$setting['setting_key']]=(float)$setting['setting_value'];
  foreach($items as $p){$stmt=$db->prepare('INSERT INTO order_items(order_id,product_id,seller_id,title_snapshot,unit_price,quantity) VALUES(?,?,?,?,?,?)');$stmt->bind_param('iiisdi',$oid,$p['id'],$p['seller_id'],$p['title'],$p['unit_price'],$p['buy_quantity']);$stmt->execute();$itemId=$stmt->insert_id;$gross=(float)$p['unit_price']*(int)$p['buy_quantity'];$rate=$p['sale_type']==='auction'?($settings['auction_commission']??5.0):($settings['standard_commission']??3.0);$commission=max($settings['minimum_commission']??0.0,round($gross*$rate/100,2));$commission=min($gross,$commission);$stmt=$db->prepare('INSERT INTO commissions(order_item_id,percentage,amount) VALUES(?,?,?)');$stmt->bind_param('idd',$itemId,$rate,$commission);$stmt->execute();$net=$gross-$commission;$stmt=$db->prepare('UPDATE wallets SET pending_balance=pending_balance+? WHERE user_id=?');$stmt->bind_param('di',$net,$p['seller_id']);$stmt->execute();$stmt=$db->prepare("UPDATE products SET status=IF(quantity=?,'sold',status),quantity=quantity-? WHERE id=?");$stmt->bind_param('iii',$p['buy_quantity'],$p['buy_quantity'],$p['id']);$stmt->execute();notify_user($db,(int)$p['seller_id'],'new_order','New order received',$p['title'].' was ordered. Approve it from Seller Orders.',['order_id'=>$oid,'order_item_id'=>$itemId]);}
  $payStatus=$payment==='cash_on_delivery'?'pending':'completed';$ref='PAY-'.$number;$paid=$payStatus==='completed'?date('Y-m-d H:i:s'):null;$stmt=$db->prepare('INSERT INTO payments(order_id,method,amount,transaction_reference,status,paid_at) VALUES(?,?,?,?,?,?)');$stmt->bind_param('isdsss',$oid,$payment,$total,$ref,$payStatus,$paid);$stmt->execute();if($payment==='wallet'){$negative=-$total;$stmt=$db->prepare("INSERT INTO wallet_transactions(wallet_id,type,amount,status,reference,description) VALUES(?,'purchase',?,'completed',?,'Marketplace purchase')");$stmt->bind_param('ids',$wallet['id'],$negative,$number);$stmt->execute();}$tracking='TRK-'.$number;$stmt=$db->prepare("INSERT INTO deliveries(order_id,tracking_number,status,estimated_delivery) VALUES(?,?,'pending',DATE_ADD(NOW(),INTERVAL 4 DAY))");$stmt->bind_param('is',$oid,$tracking);$stmt->execute();$stmt=$db->prepare('DELETE ci FROM cart_items ci JOIN carts c ON c.id=ci.cart_id WHERE c.user_id=?');$stmt->bind_param('i',$uid);$stmt->execute();$db->commit();ok(['order_id'=>$oid,'order_number'=>$number,'total'=>$total],'Order placed.',201);
 }catch(Throwable $e){$db->rollback();throw $e;}
}
if(method()==='PATCH'&&$action==='confirm-delivery'){
 require_role('buyer');$in=input();$orderId=int_value($in['order_id']??null,'order');$db->begin_transaction();
 try{
  $stmt=$db->prepare("SELECT o.order_number,d.status delivery_status FROM orders o JOIN deliveries d ON d.order_id=o.id WHERE o.id=? AND o.buyer_id=? FOR UPDATE");$stmt->bind_param('ii',$orderId,$uid);$order=db_one($stmt);if(!$order)fail('Order not found.',404);
  if($order['delivery_status']==='delivered'){$db->commit();ok(['order_id'=>$orderId,'status'=>'delivered'],'Delivery was already confirmed.');}
  if(!in_array($order['delivery_status'],['in_transit','out_for_delivery'],true))fail('This order is not ready for delivery confirmation.',409);
  $stmt=$db->prepare("SELECT oi.* FROM order_items oi WHERE oi.order_id=? FOR UPDATE");$stmt->bind_param('i',$orderId);$items=db_all($stmt);$delivered=0;
  foreach($items as $row){
   if(in_array($row['status'],['delivered','rejected'],true))continue;
   $stmt=$db->prepare("UPDATE order_items SET status='delivered' WHERE id=?");$stmt->bind_param('i',$row['id']);$stmt->execute();
   $stmt=$db->prepare('SELECT (oi.unit_price*oi.quantity-COALESCE(c.amount,0)) net FROM order_items oi LEFT JOIN commissions c ON c.order_item_id=oi.id WHERE oi.id=?');$stmt->bind_param('i',$row['id']);$net=(float)(db_one($stmt)['net']??0);
   $stmt=$db->prepare('UPDATE wallets SET pending_balance=GREATEST(0,pending_balance-?),available_balance=available_balance+? WHERE user_id=?');$stmt->bind_param('ddi',$net,$net,$row['seller_id']);$stmt->execute();
   $reference=$order['order_number'].'-I'.$row['id'];$stmt=$db->prepare("INSERT INTO wallet_transactions(wallet_id,type,amount,status,reference,description) SELECT id,'sale',?,'completed',?,'Buyer confirmed delivery' FROM wallets WHERE user_id=?");$stmt->bind_param('dsi',$net,$reference,$row['seller_id']);$stmt->execute();
   notify_user($db,(int)$row['seller_id'],'delivery_confirmed','Delivery confirmed','The buyer confirmed delivery for order #'.$order['order_number'].'.',['order_id'=>$orderId,'order_item_id'=>(int)$row['id']]);$delivered++;
  }
  $stmt=$db->prepare("UPDATE orders SET status='delivered' WHERE id=?");$stmt->bind_param('i',$orderId);$stmt->execute();
  $stmt=$db->prepare("UPDATE deliveries SET status='delivered',delivered_at=NOW() WHERE order_id=?");$stmt->bind_param('i',$orderId);$stmt->execute();
  $stmt=$db->prepare("UPDATE payments SET status='completed',paid_at=COALESCE(paid_at,NOW()) WHERE order_id=? AND status='pending'");$stmt->bind_param('i',$orderId);$stmt->execute();
  notify_user($db,$uid,'delivery_confirmed','Order delivered','You confirmed receipt of order #'.$order['order_number'].'.',['order_id'=>$orderId]);$db->commit();ok(['order_id'=>$orderId,'status'=>'delivered','items_updated'=>$delivered],'Delivery confirmed.');
 }catch(Throwable $e){$db->rollback();throw $e;}
}
if(method()==='PATCH'){$in=input();$item=int_value($in['item_id']??null,'order item');$status=$in['status']??'';if(!in_array($status,['approved','rejected','processing','shipped','delivered'],true))fail('Invalid order status.',422);$db->begin_transaction();try{$sql="SELECT oi.*,o.buyer_id,o.order_number FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.id=?".($u['role']==='seller'?' AND oi.seller_id=?':'').' FOR UPDATE';if($u['role']!=='seller')require_role('admin');$stmt=$db->prepare($sql);if($u['role']==='seller')$stmt->bind_param('ii',$item,$uid);else$stmt->bind_param('i',$item);$row=db_one($stmt);if(!$row)fail('Order item not found.',404);$allowed=['pending'=>['approved','rejected'],'approved'=>['processing','shipped','rejected'],'processing'=>['shipped','rejected'],'shipped'=>['delivered'],'delivered'=>[],'rejected'=>[]];$old=$row['status'];if($old!==$status&&!in_array($status,$allowed[$old]??[],true))fail('This order status change is not allowed.',409);if($old!==$status){$stmt=$db->prepare('UPDATE order_items SET status=? WHERE id=?');$stmt->bind_param('si',$status,$item);$stmt->execute();$stmt=$db->prepare('UPDATE orders SET status=? WHERE id=?');$stmt->bind_param('si',$status,$row['order_id']);$stmt->execute();if($status==='shipped'||$status==='delivered'){$delivery=$status==='shipped'?'in_transit':'delivered';$stmt=$db->prepare("UPDATE deliveries SET status=?,delivered_at=IF(?='delivered',NOW(),delivered_at) WHERE order_id=?");$stmt->bind_param('ssi',$delivery,$delivery,$row['order_id']);$stmt->execute();}if($status==='delivered'){$stmt=$db->prepare('SELECT (oi.unit_price*oi.quantity-c.amount) net FROM order_items oi JOIN commissions c ON c.order_item_id=oi.id WHERE oi.id=?');$stmt->bind_param('i',$item);$net=(float)(db_one($stmt)['net']??0);$stmt=$db->prepare('UPDATE wallets SET pending_balance=GREATEST(0,pending_balance-?),available_balance=available_balance+? WHERE user_id=?');$stmt->bind_param('ddi',$net,$net,$row['seller_id']);$stmt->execute();$stmt=$db->prepare("INSERT INTO wallet_transactions(wallet_id,type,amount,status,reference,description) SELECT id,'sale',?,'completed',?,'Order delivered' FROM wallets WHERE user_id=?");$stmt->bind_param('dsi',$net,$row['order_number'],$row['seller_id']);$stmt->execute();}notify_user($db,(int)$row['buyer_id'],'order_status','Order status updated','Order #'.$row['order_number'].' is now '.$status.'.',['order_id'=>(int)$row['order_id']]);if($status==='shipped')notify_admins($db,'delivery_handover','Item handed to delivery','Order #'.$row['order_number'].' was handed to delivery.',['order_id'=>(int)$row['order_id']]);}$db->commit();ok(['item_id'=>$item,'status'=>$status],'Order status updated.');}catch(Throwable $e){$db->rollback();throw $e;}}fail('Method not allowed.',405);
