<?php
require __DIR__.'/bootstrap.php';$u=require_user();$uid=(int)$u['id'];$action=$_GET['action']??'';
if(method()==='GET'){
 if($u['role']==='seller'){$stmt=$db->prepare("SELECT o.id,o.order_number,o.status,o.total_amount,o.shipping_amount,o.shipping_address,o.placed_at,o.shipping_name,oi.id item_id,oi.product_id,oi.title_snapshot,oi.unit_price,oi.quantity,oi.status item_status,p.condition_label,p.sale_type,p.location,p.description,c.name category,pi.image_url image,d.tracking_number,d.status delivery_status FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id JOIN categories c ON c.id=p.category_id LEFT JOIN product_images pi ON pi.product_id=p.id AND pi.is_primary=1 LEFT JOIN deliveries d ON d.order_id=o.id WHERE oi.seller_id=? ORDER BY o.placed_at DESC");$stmt->bind_param('i',$uid);ok(db_all($stmt));}
 $stmt=$db->prepare("SELECT o.*,d.carrier,d.tracking_number,d.status delivery_status,d.estimated_delivery,d.delivered_at FROM orders o LEFT JOIN deliveries d ON d.order_id=o.id WHERE o.buyer_id=? ORDER BY o.placed_at DESC");$stmt->bind_param('i',$uid);$orders=db_all($stmt);foreach($orders as &$order){$itemStmt=$db->prepare("SELECT oi.id,oi.product_id,oi.title_snapshot,oi.unit_price,oi.quantity,oi.status,pi.image_url image,p.slug,p.condition_label,p.sale_type FROM order_items oi JOIN products p ON p.id=oi.product_id LEFT JOIN product_images pi ON pi.product_id=p.id AND pi.is_primary=1 WHERE oi.order_id=?");$itemStmt->bind_param('i',$order['id']);$order['items']=db_all($itemStmt);}ok($orders);
}
if(method()==='POST'&&$action==='checkout'){
 require_role('buyer','admin');$in=input();$name=text_value($in,'shipping_name',160);$email=text_value($in,'shipping_email',190);$phone=text_value($in,'shipping_phone',30);$address=text_value($in,'shipping_address',1000);$payment=$in['payment_method']??'card';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($payment,['card','wallet','cash_on_delivery'],true))fail('Invalid checkout details.',422);
 $requested=$in['items']??[];$db->begin_transaction();
 try{
  if(!$requested){$stmt=$db->prepare('SELECT ci.product_id,ci.quantity FROM carts c JOIN cart_items ci ON ci.cart_id=c.id WHERE c.user_id=?');$stmt->bind_param('i',$uid);$requested=db_all($stmt);}if(!$requested)fail('Your cart is empty.',422);
  $items=[];$subtotal=0;foreach($requested as $it){$pid=int_value($it['product_id']??null,'product');$qty=max(1,(int)($it['quantity']??1));$stmt=$db->prepare("SELECT p.id,p.seller_id,p.title,p.price,p.quantity,p.status,p.sale_type,a.id auction_id,a.buy_now_price,a.status auction_status FROM products p LEFT JOIN auctions a ON a.product_id=p.id WHERE p.id=? FOR UPDATE");$stmt->bind_param('i',$pid);$p=db_one($stmt);if(!$p)fail('One or more products are unavailable.',409);$isAuction=$p['sale_type']==='auction';$unitPrice=$isAuction?(float)$p['buy_now_price']:(float)$p['price'];if($p['status']!=='active'||$qty>(int)$p['quantity']||$unitPrice<=0||($isAuction&&($p['auction_status']!=='live'||$qty!==1)))fail('One or more products are unavailable.',409);$p['unit_price']=$unitPrice;$p['buy_quantity']=$qty;$items[]=$p;$subtotal+=$unitPrice*$qty;}
  $shipping=15.00;$tax=0.00;$total=$subtotal+$shipping;if($payment==='wallet'){$stmt=$db->prepare('SELECT id,available_balance FROM wallets WHERE user_id=? FOR UPDATE');$stmt->bind_param('i',$uid);$wallet=db_one($stmt);if(!$wallet||(float)$wallet['available_balance']<$total)fail('Insufficient wallet balance.',409);$stmt=$db->prepare('UPDATE wallets SET available_balance=available_balance-? WHERE id=?');$stmt->bind_param('di',$total,$wallet['id']);$stmt->execute();}
  $number='RT-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(2)));$status=$payment==='cash_on_delivery'?'approved':'paid';$stmt=$db->prepare('INSERT INTO orders(order_number,buyer_id,subtotal,shipping_amount,tax_amount,total_amount,status,shipping_name,shipping_email,shipping_phone,shipping_address) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$stmt->bind_param('siddddsssss',$number,$uid,$subtotal,$shipping,$tax,$total,$status,$name,$email,$phone,$address);$stmt->execute();$oid=$stmt->insert_id;
  foreach($items as $p){$stmt=$db->prepare('INSERT INTO order_items(order_id,product_id,seller_id,title_snapshot,unit_price,quantity) VALUES(?,?,?,?,?,?)');$stmt->bind_param('iiisdi',$oid,$p['id'],$p['seller_id'],$p['title'],$p['unit_price'],$p['buy_quantity']);$stmt->execute();$itemId=$stmt->insert_id;$gross=(float)$p['unit_price']*(int)$p['buy_quantity'];$commission=round($gross*.03,2);$stmt=$db->prepare('INSERT INTO commissions(order_item_id,percentage,amount) VALUES(?,3.00,?)');$stmt->bind_param('id',$itemId,$commission);$stmt->execute();$net=$gross-$commission;$stmt=$db->prepare('UPDATE wallets SET pending_balance=pending_balance+? WHERE user_id=?');$stmt->bind_param('di',$net,$p['seller_id']);$stmt->execute();$stmt=$db->prepare("UPDATE products SET quantity=quantity-?,status=IF(quantity-?=0,'sold',status) WHERE id=?");$stmt->bind_param('iii',$p['buy_quantity'],$p['buy_quantity'],$p['id']);$stmt->execute();if($p['sale_type']==='auction'){$stmt=$db->prepare("UPDATE auctions SET status='ended',closed_at=NOW() WHERE id=?");$stmt->bind_param('i',$p['auction_id']);$stmt->execute();}}
  $payStatus=$payment==='cash_on_delivery'?'pending':'completed';$ref='PAY-'.$number;$paid=$payStatus==='completed'?date('Y-m-d H:i:s'):null;$stmt=$db->prepare('INSERT INTO payments(order_id,method,amount,transaction_reference,status,paid_at) VALUES(?,?,?,?,?,?)');$stmt->bind_param('isdsss',$oid,$payment,$total,$ref,$payStatus,$paid);$stmt->execute();if($payment==='wallet'){$negative=-$total;$stmt=$db->prepare("INSERT INTO wallet_transactions(wallet_id,type,amount,status,reference,description) VALUES(?,'purchase',?,'completed',?,'Marketplace purchase')");$stmt->bind_param('ids',$wallet['id'],$negative,$number);$stmt->execute();}$tracking='TRK-'.$number;$stmt=$db->prepare("INSERT INTO deliveries(order_id,tracking_number,status,estimated_delivery) VALUES(?,?,'pending',DATE_ADD(NOW(),INTERVAL 4 DAY))");$stmt->bind_param('is',$oid,$tracking);$stmt->execute();$stmt=$db->prepare('DELETE ci FROM cart_items ci JOIN carts c ON c.id=ci.cart_id WHERE c.user_id=?');$stmt->bind_param('i',$uid);$stmt->execute();$db->commit();ok(['order_id'=>$oid,'order_number'=>$number,'total'=>$total],'Order placed.',201);
 }catch(Throwable $e){$db->rollback();throw $e;}
}
if(method()==='PATCH'){$in=input();$item=int_value($in['item_id']??null,'order item');$status=$in['status']??'';if(!in_array($status,['approved','rejected','processing','shipped','delivered'],true))fail('Invalid order status.',422);$db->begin_transaction();try{if($u['role']==='seller'){$stmt=$db->prepare('UPDATE order_items SET status=? WHERE id=? AND seller_id=?');$stmt->bind_param('sii',$status,$item,$uid);}else{require_role('admin');$stmt=$db->prepare('UPDATE order_items SET status=? WHERE id=?');$stmt->bind_param('si',$status,$item);}$stmt->execute();if($stmt->affected_rows===0)fail('Order item not found.',404);$stmt=$db->prepare('SELECT order_id FROM order_items WHERE id=?');$stmt->bind_param('i',$item);$row=db_one($stmt);$stmt=$db->prepare('UPDATE orders SET status=? WHERE id=?');$stmt->bind_param('si',$status,$row['order_id']);$stmt->execute();if($status==='shipped'||$status==='delivered'){$delivery=$status==='shipped'?'in_transit':'delivered';$stmt=$db->prepare('UPDATE deliveries SET status=?,delivered_at=IF(?=\'delivered\',NOW(),delivered_at) WHERE order_id=?');$stmt->bind_param('ssi',$delivery,$delivery,$row['order_id']);$stmt->execute();}$db->commit();ok(null,'Order status updated.');}catch(Throwable $e){$db->rollback();throw $e;}}fail('Method not allowed.',405);
