<?php
require __DIR__.'/bootstrap.php';
$u=require_user();$uid=(int)$u['id'];$type=$_GET['type']??'';$format=strtolower($_GET['format']??'pdf');

function report_text(string $value): string { $value=iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',$value)?:$value;return str_replace(['\\','(',')'],['\\\\','\(','\)'],$value); }
function stream_pdf(string $title,array $lines,string $filename): never {
 $commands="BT /F1 18 Tf 50 790 Td (".report_text($title).") Tj /F1 10 Tf 0 -24 Td";foreach(array_slice($lines,0,48) as $line)$commands.=" (".report_text((string)$line).") Tj 0 -14 Td";$commands.=" ET";
 $objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',2=>'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',3=>'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',4=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',5=>'<< /Length '.strlen($commands).' >>'."\nstream\n$commands\nendstream"];
 $pdf="%PDF-1.4\n";$offsets=[0=>0];foreach($objects as $number=>$body){$offsets[$number]=strlen($pdf);$pdf.="$number 0 obj\n$body\nendobj\n";}$xref=strlen($pdf);$pdf.="xref\n0 6\n0000000000 65535 f \n";for($i=1;$i<=5;$i++)$pdf.=sprintf('%010d 00000 n ', $offsets[$i])."\n";$pdf.="trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";
 header_remove('Content-Type');header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Content-Length: '.strlen($pdf));echo $pdf;exit;
}
function stream_csv(array $header,array $rows,string $filename): never { header_remove('Content-Type');header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$filename.'"');$out=fopen('php://output','w');fputcsv($out,$header);foreach($rows as $row)fputcsv($out,$row);fclose($out);exit; }

if($type==='admin-sales'||$type==='admin-commissions'){
 require_role('admin');$rows=$db->query("SELECT o.order_number,o.placed_at,o.status,oi.title_snapshot,CONCAT(s.first_name,' ',s.last_name) seller,oi.unit_price*oi.quantity gross,COALESCE(c.amount,0) commission FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN users s ON s.id=oi.seller_id LEFT JOIN commissions c ON c.order_item_id=oi.id ORDER BY o.placed_at DESC")->fetch_all(MYSQLI_ASSOC);$total=array_sum(array_column($rows,'gross'));$commission=array_sum(array_column($rows,'commission'));if($format==='csv')stream_csv(['Order','Date','Status','Item','Seller','Gross','Commission'],array_map(fn($r)=>[$r['order_number'],$r['placed_at'],$r['status'],$r['title_snapshot'],$r['seller'],$r['gross'],$r['commission']],$rows),'retrade-sales-report.csv');$lines=['Generated: '.date('Y-m-d H:i'),'Total sales: $'.number_format($total,2),'Total commissions: $'.number_format($commission,2),''];foreach($rows as $r)$lines[]=$r['order_number'].' | '.$r['title_snapshot'].' | $'.number_format((float)$r['gross'],2).' | fee $'.number_format((float)$r['commission'],2);stream_pdf('ReTrade Sales & Commission Report',$lines,'retrade-sales-commission-report.pdf');
}
if($type==='seller-earnings'){
 require_role('seller','admin');$sellerId=$u['role']==='admin'&&isset($_GET['seller_id'])?int_value($_GET['seller_id'],'seller'):$uid;$month=preg_match('/^\d{4}-\d{2}$/',(string)($_GET['month']??''))?$_GET['month']:date('Y-m');$stmt=$db->prepare("SELECT o.order_number,o.placed_at,oi.title_snapshot,oi.unit_price*oi.quantity gross,COALESCE(c.amount,0) commission,(oi.unit_price*oi.quantity-COALESCE(c.amount,0)) net FROM order_items oi JOIN orders o ON o.id=oi.order_id LEFT JOIN commissions c ON c.order_item_id=oi.id WHERE oi.seller_id=? AND DATE_FORMAT(o.placed_at,'%Y-%m')=? ORDER BY o.placed_at");$stmt->bind_param('is',$sellerId,$month);$rows=db_all($stmt);$gross=array_sum(array_column($rows,'gross'));$fees=array_sum(array_column($rows,'commission'));$lines=['Month: '.$month,'Gross sales: $'.number_format($gross,2),'Commission deducted: $'.number_format($fees,2),'Net earnings: $'.number_format($gross-$fees,2),''];foreach($rows as $r)$lines[]=$r['order_number'].' | '.$r['title_snapshot'].' | net $'.number_format((float)$r['net'],2);stream_pdf('Monthly Earnings Report',$lines,'earnings-'.$month.'.pdf');
}
if($type==='receipt'){
 $orderId=int_value($_GET['order_id']??null,'order');$sql="SELECT o.*,oi.title_snapshot,oi.quantity,oi.unit_price,CONCAT(s.first_name,' ',s.last_name) seller,COALESCE(c.amount,0) commission FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN users s ON s.id=oi.seller_id LEFT JOIN commissions c ON c.order_item_id=oi.id WHERE o.id=?";if($u['role']==='buyer')$sql.=' AND o.buyer_id='.(int)$uid;elseif($u['role']==='seller')$sql.=' AND oi.seller_id='.(int)$uid;$stmt=$db->prepare($sql);$stmt->bind_param('i',$orderId);$rows=db_all($stmt);if(!$rows)fail('Receipt not found.',404);$first=$rows[0];$lines=['Order: '.$first['order_number'],'Date: '.$first['placed_at'],'Status: '.$first['status'],'Buyer: '.$first['shipping_name'],'Address: '.$first['shipping_address'],''];foreach($rows as $r)$lines[]=$r['title_snapshot'].' x'.$r['quantity'].' - $'.number_format((float)$r['unit_price']*(int)$r['quantity'],2);$lines[]='';$lines[]='Shipping: $'.number_format((float)$first['shipping_amount'],2);$lines[]='Total: $'.number_format((float)$first['total_amount'],2);stream_pdf('ReTrade Sale Receipt',$lines,'receipt-'.$first['order_number'].'.pdf');
}
fail('Unknown report type.',404);
